# Copyright (c) 2022-2026, The Isaac Lab Project Developers (https://github.com/isaac-sim/IsaacLab/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

__all__ = [
    "ArticulationRootBaseCfg",
    "ArticulationRootFragment",
    "ArticulationRootPropertiesCfg",
    "AssetConverterBase",
    "AssetConverterBaseCfg",
    "BaseFrameView",
    "BoundingCubePropertiesCfg",
    "BoundingSpherePropertiesCfg",
    "CableCfg",
    "CableMaterialCfg",
    "CapsuleCfg",
    "CollisionBaseCfg",
    "CollisionFragment",
    "CollisionPropertiesCfg",
    "ConeCfg",
    "ConvexDecompositionPropertiesCfg",
    "ConvexHullPropertiesCfg",
    "CuboidCfg",
    "CylinderCfg",
    "CylinderLightCfg",
    "DeformableBodyMaterialBaseCfg",
    "DeformableBodyMaterialCfg",
    "DeformableBodyPropertiesBaseCfg",
    "DeformableBodyPropertiesCfg",
    "DeformableObjectSpawnerCfg",
    "DiskLightCfg",
    "DistantLightCfg",
    "DomeLightCfg",
    "FisheyeCameraCfg",
    "FixedTendonFragment",
    "FixedTendonPropertiesCfg",
    "FrameView",
    "GlassMdlCfg",
    "GroundPlaneCfg",
    "JointDriveBaseCfg",
    "JointDriveFragment",
    "JointDrivePropertiesCfg",
    "LightCfg",
    "MESH_APPROXIMATION_TOKENS",
    "MassCfg",
    "MassFragment",
    "MassPropertiesCfg",
    "MdlFileCfg",
    "MeshCapsuleCfg",
    "MeshCfg",
    "MeshCollisionBaseCfg",
    "MeshCollisionFragment",
    "MeshCollisionPropertiesCfg",
    "MeshConeCfg",
    "MeshConverter",
    "MeshConverterCfg",
    "MeshCuboidCfg",
    "MeshCylinderCfg",
    "MeshRectangleCfg",
    "MeshSphereCfg",
    "MjcfConverter",
    "MjcfConverterCfg",
    "MjcfFileCfg",
    "MujocoJointDrivePropertiesCfg",
    "MujocoRigidBodyPropertiesCfg",
    "MultiAssetSpawnerCfg",
    "MultiUsdFileCfg",
    "NewtonArticulationRootPropertiesCfg",
    "NewtonCollisionPropertiesCfg",
    "NewtonJointDrivePropertiesCfg",
    "NewtonMaterialPropertiesCfg",
    "NewtonMeshCollisionPropertiesCfg",
    "NewtonRigidBodyPropertiesCfg",
    "NewtonSDFCollisionPropertiesCfg",
    "OpenCvDistortionCfg",
    "OpenCvFisheyeDistortionCfg",
    "OpenCvPinholeDistortionCfg",
    "PHYSX_MESH_COLLISION_CFGS",
    "PhysicsMaterialCfg",
    "PhysxArticulationRootPropertiesCfg",
    "PhysxCollisionPropertiesCfg",
    "PhysxConvexDecompositionPropertiesCfg",
    "PhysxConvexHullPropertiesCfg",
    "PhysxDeformableBodyMaterialCfg",
    "PhysxDeformableBodyPropertiesCfg",
    "PhysxDeformableCollisionPropertiesCfg",
    "PhysxFixedTendonPropertiesCfg",
    "PhysxJointDrivePropertiesCfg",
    "PhysxRigidBodyMaterialCfg",
    "PhysxRigidBodyPropertiesCfg",
    "PhysxSDFMeshPropertiesCfg",
    "PhysxSpatialTendonPropertiesCfg",
    "PhysxSurfaceDeformableBodyMaterialCfg",
    "PhysxTriangleMeshPropertiesCfg",
    "PhysxTriangleMeshSimplificationPropertiesCfg",
    "PinholeCameraCfg",
    "PreviewSurfaceCfg",
    "RigidBodyBaseCfg",
    "RigidBodyFragment",
    "RigidBodyMaterialCfg",
    "RigidBodyPropertiesCfg",
    "RigidObjectSpawnerCfg",
    "SDFMeshPropertiesCfg",
    "SchemaFragment",
    "SensorFrameCfg",
    "ShapeCfg",
    "SimulationCfg",
    "SimulationContext",
    "SpatialTendonFragment",
    "SpatialTendonPropertiesCfg",
    "SpawnerCfg",
    "SphereCfg",
    "SphereLightCfg",
    "SurfaceDeformableBodyMaterialBaseCfg",
    "SurfaceDeformableBodyMaterialCfg",
    "TriangleMeshPropertiesCfg",
    "TriangleMeshSimplificationPropertiesCfg",
    "USD_MESH_COLLISION_CFGS",
    "UrdfConverter",
    "UrdfConverterCfg",
    "UrdfFileCfg",
    "UsdFileCfg",
    "UsdFileWithCompliantContactCfg",
    "UsdFrameView",
    "UsdPhysicsCollisionCfg",
    "UsdPhysicsDriveCfg",
    "UsdPhysicsMeshCollisionCfg",
    "UsdPhysicsRigidBodyCfg",
    "VisualMaterialCfg",
    "XformPrimView",
    "activate_contact_sensors",
    "add_labels",
    "add_reference_to_stage",
    "add_usd_reference",
    "apply_articulation_root_properties",
    "apply_collision_properties",
    "apply_drive",
    "apply_fixed_tendon_properties",
    "apply_joint_drive_properties",
    "apply_mass_properties",
    "apply_mesh_collision",
    "apply_mesh_collision_properties",
    "apply_namespaced",
    "apply_nested",
    "apply_rigid_body_properties",
    "apply_spatial_tendon_properties",
    "bind_physics_material",
    "bind_visual_material",
    "build_simulation_context",
    "change_prim_property",
    "check_missing_labels",
    "clear_stage",
    "clone",
    "close_stage",
    "convert_world_pose_to_local",
    "count_total_labels",
    "create_new_stage",
    "create_prim",
    "define_articulation_root_properties",
    "define_collision_properties",
    "define_deformable_body_properties",
    "define_deformable_curve_properties",
    "define_mass_properties",
    "define_mesh_collision_properties",
    "define_prim",
    "define_rigid_body_properties",
    "delete_prim",
    "disable_extension",
    "enable_extension",
    "export_prim_to_file",
    "find_first_matching_prim",
    "find_global_fixed_joint_prim",
    "find_matching_prim_paths",
    "find_matching_prims",
    "get_all_matching_child_prims",
    "get_current_stage",
    "get_current_stage_id",
    "get_extension_path",
    "get_first_matching_ancestor_prim",
    "get_first_matching_child_prim",
    "get_labels",
    "get_next_free_path",
    "get_next_free_prim_path",
    "get_prim_at_path",
    "get_prim_path",
    "get_prim_type_name",
    "get_stage_up_axis",
    "get_usd_references",
    "has_deformable_body_api",
    "has_deformable_curve_api",
    "is_current_stage_in_memory",
    "is_prim_path_valid",
    "make_uninstanceable",
    "matches_path_expr_prefix",
    "modify_articulation_root_properties",
    "modify_collision_properties",
    "modify_deformable_body_properties",
    "modify_fixed_tendon_properties",
    "modify_joint_drive_properties",
    "modify_mass_properties",
    "modify_mesh_collision_properties",
    "modify_rigid_body_properties",
    "modify_spatial_tendon_properties",
    "open_stage",
    "remove_labels",
    "resolve_matching_prims_from_source",
    "resolve_paths",
    "resolve_prim_pose",
    "resolve_prim_scale",
    "safe_set_attribute_on_usd_prim",
    "safe_set_attribute_on_usd_schema",
    "save_stage",
    "select_usd_variants",
    "set_prim_visibility",
    "show_stage_in_viewport",
    "spawn_cable",
    "spawn_camera",
    "spawn_capsule",
    "spawn_cone",
    "spawn_cuboid",
    "spawn_cylinder",
    "spawn_deformable_body_material",
    "spawn_from_mdl_file",
    "spawn_from_mjcf",
    "spawn_from_urdf",
    "spawn_from_usd",
    "spawn_from_usd_with_compliant_contact_material",
    "spawn_ground_plane",
    "spawn_light",
    "spawn_mesh_capsule",
    "spawn_mesh_cone",
    "spawn_mesh_cuboid",
    "spawn_mesh_cylinder",
    "spawn_mesh_rectangle",
    "spawn_mesh_sphere",
    "spawn_multi_asset",
    "spawn_multi_usd_file",
    "spawn_preview_surface",
    "spawn_rigid_body_material",
    "spawn_sensor_frame",
    "spawn_sphere",
    "standardize_xform_ops",
    "traverse_stage",
    "update_stage",
    "use_stage",
    "validate_standard_xform_ops",
]

from .converters import (
    AssetConverterBase,
    AssetConverterBaseCfg,
    MeshConverter,
    MeshConverterCfg,
    MjcfConverter,
    MjcfConverterCfg,
    UrdfConverter,
    UrdfConverterCfg,
)
from .schemas import (
    ArticulationRootBaseCfg,
    ArticulationRootFragment,
    ArticulationRootPropertiesCfg,
    BoundingCubePropertiesCfg,
    BoundingSpherePropertiesCfg,
    CollisionBaseCfg,
    CollisionFragment,
    ConvexDecompositionPropertiesCfg,
    ConvexHullPropertiesCfg,
    DeformableBodyPropertiesBaseCfg,
    DeformableBodyPropertiesCfg,
    FixedTendonFragment,
    FixedTendonPropertiesCfg,
    JointDriveBaseCfg,
    JointDriveFragment,
    MESH_APPROXIMATION_TOKENS,
    MassCfg,
    MassFragment,
    MassPropertiesCfg,
    MeshCollisionBaseCfg,
    MeshCollisionFragment,
    MeshCollisionPropertiesCfg,
    PHYSX_MESH_COLLISION_CFGS,
    PhysxJointDrivePropertiesCfg,
    PhysxRigidBodyPropertiesCfg,
    RigidBodyBaseCfg,
    RigidBodyFragment,
    SDFMeshPropertiesCfg,
    SchemaFragment,
    SpatialTendonFragment,
    SpatialTendonPropertiesCfg,
    TriangleMeshPropertiesCfg,
    TriangleMeshSimplificationPropertiesCfg,
    USD_MESH_COLLISION_CFGS,
    UsdPhysicsCollisionCfg,
    UsdPhysicsDriveCfg,
    UsdPhysicsMeshCollisionCfg,
    UsdPhysicsRigidBodyCfg,
    activate_contact_sensors,
    apply_articulation_root_properties,
    apply_collision_properties,
    apply_drive,
    apply_fixed_tendon_properties,
    apply_joint_drive_properties,
    apply_mass_properties,
    apply_mesh_collision,
    apply_mesh_collision_properties,
    apply_namespaced,
    apply_rigid_body_properties,
    apply_spatial_tendon_properties,
    define_articulation_root_properties,
    define_collision_properties,
    define_deformable_body_properties,
    define_deformable_curve_properties,
    define_mass_properties,
    define_mesh_collision_properties,
    define_rigid_body_properties,
    modify_articulation_root_properties,
    modify_collision_properties,
    modify_deformable_body_properties,
    modify_fixed_tendon_properties,
    modify_joint_drive_properties,
    modify_mass_properties,
    modify_mesh_collision_properties,
    modify_rigid_body_properties,
    modify_spatial_tendon_properties,
)
from .simulation_cfg import SimulationCfg
from .simulation_context import SimulationContext, build_simulation_context

from .spawners import (
    CableCfg,
    CableMaterialCfg,
    CapsuleCfg,
    ConeCfg,
    CuboidCfg,
    CylinderCfg,
    CylinderLightCfg,
    DeformableBodyMaterialBaseCfg,
    DeformableBodyMaterialCfg,
    DeformableObjectSpawnerCfg,
    DiskLightCfg,
    DistantLightCfg,
    DomeLightCfg,
    FisheyeCameraCfg,
    GlassMdlCfg,
    GroundPlaneCfg,
    LightCfg,
    MdlFileCfg,
    MeshCapsuleCfg,
    MeshCfg,
    MeshConeCfg,
    MeshCuboidCfg,
    MeshCylinderCfg,
    MeshRectangleCfg,
    MeshSphereCfg,
    MjcfFileCfg,
    MultiAssetSpawnerCfg,
    MultiUsdFileCfg,
    OpenCvDistortionCfg,
    OpenCvFisheyeDistortionCfg,
    OpenCvPinholeDistortionCfg,
    PhysicsMaterialCfg,
    PinholeCameraCfg,
    PreviewSurfaceCfg,
    RigidBodyMaterialCfg,
    RigidObjectSpawnerCfg,
    SensorFrameCfg,
    ShapeCfg,
    SpawnerCfg,
    SphereCfg,
    SphereLightCfg,
    SurfaceDeformableBodyMaterialBaseCfg,
    SurfaceDeformableBodyMaterialCfg,
    UrdfFileCfg,
    UsdFileCfg,
    UsdFileWithCompliantContactCfg,
    VisualMaterialCfg,
    spawn_cable,
    spawn_camera,
    spawn_capsule,
    spawn_cone,
    spawn_cuboid,
    spawn_cylinder,
    spawn_deformable_body_material,
    spawn_from_mdl_file,
    spawn_from_mjcf,
    spawn_from_urdf,
    spawn_from_usd,
    spawn_from_usd_with_compliant_contact_material,
    spawn_ground_plane,
    spawn_light,
    spawn_mesh_capsule,
    spawn_mesh_cone,
    spawn_mesh_cuboid,
    spawn_mesh_cylinder,
    spawn_mesh_rectangle,
    spawn_mesh_sphere,
    spawn_multi_asset,
    spawn_multi_usd_file,
    spawn_preview_surface,
    spawn_rigid_body_material,
    spawn_sensor_frame,
    spawn_sphere,
)
from .utils import (
    add_labels,
    add_reference_to_stage,
    add_usd_reference,
    apply_nested,
    bind_physics_material,
    bind_visual_material,
    change_prim_property,
    check_missing_labels,
    clear_stage,
    clone,
    close_stage,
    convert_world_pose_to_local,
    count_total_labels,
    create_new_stage,
    create_prim,
    disable_extension,
    define_prim,
    delete_prim,
    enable_extension,
    export_prim_to_file,
    find_first_matching_prim,
    find_global_fixed_joint_prim,
    find_matching_prim_paths,
    find_matching_prims,
    get_all_matching_child_prims,
    get_current_stage,
    get_current_stage_id,
    get_extension_path,
    get_first_matching_ancestor_prim,
    get_first_matching_child_prim,
    get_labels,
    get_next_free_path,
    get_next_free_prim_path,
    get_prim_at_path,
    get_prim_path,
    get_prim_type_name,
    get_stage_up_axis,
    get_usd_references,
    has_deformable_body_api,
    has_deformable_curve_api,
    is_current_stage_in_memory,
    is_prim_path_valid,
    make_uninstanceable,
    matches_path_expr_prefix,
    open_stage,
    remove_labels,
    resolve_matching_prims_from_source,
    resolve_paths,
    resolve_prim_pose,
    resolve_prim_scale,
    safe_set_attribute_on_usd_prim,
    safe_set_attribute_on_usd_schema,
    save_stage,
    select_usd_variants,
    set_prim_visibility,
    show_stage_in_viewport,
    standardize_xform_ops,
    traverse_stage,
    update_stage,
    use_stage,
    validate_standard_xform_ops,
)
from .views import (
    BaseFrameView,
    FrameView,
    UsdFrameView,
    XformPrimView,  # deprecated alias
)

# Forwarded via __getattr__ → isaaclab_newton.sim.schemas.schemas_cfg
from isaaclab_newton.sim.schemas.schemas_cfg import (
    MujocoJointDrivePropertiesCfg as MujocoJointDrivePropertiesCfg,
    MujocoRigidBodyPropertiesCfg as MujocoRigidBodyPropertiesCfg,
    NewtonArticulationRootPropertiesCfg as NewtonArticulationRootPropertiesCfg,
    NewtonCollisionPropertiesCfg as NewtonCollisionPropertiesCfg,
    NewtonJointDrivePropertiesCfg as NewtonJointDrivePropertiesCfg,
    NewtonMaterialPropertiesCfg as NewtonMaterialPropertiesCfg,
    NewtonMeshCollisionPropertiesCfg as NewtonMeshCollisionPropertiesCfg,
    NewtonRigidBodyPropertiesCfg as NewtonRigidBodyPropertiesCfg,
    NewtonSDFCollisionPropertiesCfg as NewtonSDFCollisionPropertiesCfg,
)

# Forwarded via __getattr__ → isaaclab_physx.sim.schemas.schemas_cfg
from isaaclab_physx.sim.schemas.schemas_cfg import (
    ArticulationRootPropertiesCfg as ArticulationRootPropertiesCfg,
    CollisionPropertiesCfg as CollisionPropertiesCfg,
    ConvexDecompositionPropertiesCfg as ConvexDecompositionPropertiesCfg,
    ConvexHullPropertiesCfg as ConvexHullPropertiesCfg,
    DeformableBodyPropertiesCfg as DeformableBodyPropertiesCfg,
    FixedTendonPropertiesCfg as FixedTendonPropertiesCfg,
    JointDrivePropertiesCfg as JointDrivePropertiesCfg,
    MeshCollisionPropertiesCfg as MeshCollisionPropertiesCfg,
    PhysxArticulationRootPropertiesCfg as PhysxArticulationRootPropertiesCfg,
    PhysxCollisionPropertiesCfg as PhysxCollisionPropertiesCfg,
    PhysxConvexDecompositionPropertiesCfg as PhysxConvexDecompositionPropertiesCfg,
    PhysxConvexHullPropertiesCfg as PhysxConvexHullPropertiesCfg,
    PhysxDeformableBodyPropertiesCfg as PhysxDeformableBodyPropertiesCfg,
    PhysxFixedTendonPropertiesCfg as PhysxFixedTendonPropertiesCfg,
    PhysxJointDrivePropertiesCfg as PhysxJointDrivePropertiesCfg,
    PhysxRigidBodyPropertiesCfg as PhysxRigidBodyPropertiesCfg,
    PhysxSDFMeshPropertiesCfg as PhysxSDFMeshPropertiesCfg,
    PhysxSpatialTendonPropertiesCfg as PhysxSpatialTendonPropertiesCfg,
    PhysxTriangleMeshPropertiesCfg as PhysxTriangleMeshPropertiesCfg,
    PhysxTriangleMeshSimplificationPropertiesCfg as PhysxTriangleMeshSimplificationPropertiesCfg,
    RigidBodyPropertiesCfg as RigidBodyPropertiesCfg,
    SDFMeshPropertiesCfg as SDFMeshPropertiesCfg,
    SpatialTendonPropertiesCfg as SpatialTendonPropertiesCfg,
    TriangleMeshPropertiesCfg as TriangleMeshPropertiesCfg,
    TriangleMeshSimplificationPropertiesCfg as TriangleMeshSimplificationPropertiesCfg,
)

# Forwarded via __getattr__ → isaaclab_physx.sim.spawners.materials.physics_materials_cfg
from isaaclab_physx.sim.spawners.materials.physics_materials_cfg import (
    DeformableBodyMaterialCfg as DeformableBodyMaterialCfg,
    PhysxDeformableBodyMaterialCfg as PhysxDeformableBodyMaterialCfg,
    PhysxRigidBodyMaterialCfg as PhysxRigidBodyMaterialCfg,
    PhysxSurfaceDeformableBodyMaterialCfg as PhysxSurfaceDeformableBodyMaterialCfg,
    RigidBodyMaterialCfg as RigidBodyMaterialCfg,
    SurfaceDeformableBodyMaterialCfg as SurfaceDeformableBodyMaterialCfg,
)
