# Copyright (c) 2022-2026, The Isaac Lab Project Developers (https://github.com/isaac-sim/IsaacLab/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

__all__ = [
    "ArticulationRootBaseCfg",
    "ArticulationRootFragment",
    "ArticulationRootPropertiesCfg",
    "BoundingCubePropertiesCfg",
    "BoundingSpherePropertiesCfg",
    "CollisionBaseCfg",
    "CollisionFragment",
    "CollisionPropertiesCfg",
    "ConvexDecompositionPropertiesCfg",
    "ConvexHullPropertiesCfg",
    "DeformableBodyPropertiesBaseCfg",
    "DeformableBodyPropertiesCfg",
    "FixedTendonFragment",
    "FixedTendonPropertiesCfg",
    "JointDriveBaseCfg",
    "JointDriveFragment",
    "JointDrivePropertiesCfg",
    "MESH_APPROXIMATION_TOKENS",
    "MassCfg",
    "MassFragment",
    "MassPropertiesCfg",
    "MeshCollisionBaseCfg",
    "MeshCollisionFragment",
    "MeshCollisionPropertiesCfg",
    "MujocoJointDrivePropertiesCfg",
    "MujocoRigidBodyPropertiesCfg",
    "NewtonArticulationRootPropertiesCfg",
    "NewtonCollisionPropertiesCfg",
    "NewtonJointDrivePropertiesCfg",
    "NewtonMaterialPropertiesCfg",
    "NewtonMeshCollisionPropertiesCfg",
    "NewtonRigidBodyPropertiesCfg",
    "NewtonSDFCollisionPropertiesCfg",
    "PHYSX_MESH_COLLISION_CFGS",
    "PhysxArticulationRootPropertiesCfg",
    "PhysxCollisionPropertiesCfg",
    "PhysxConvexDecompositionPropertiesCfg",
    "PhysxConvexHullPropertiesCfg",
    "PhysxDeformableBodyPropertiesCfg",
    "PhysxFixedTendonPropertiesCfg",
    "PhysxJointDrivePropertiesCfg",
    "PhysxRigidBodyPropertiesCfg",
    "PhysxSDFMeshPropertiesCfg",
    "PhysxSpatialTendonPropertiesCfg",
    "PhysxTriangleMeshPropertiesCfg",
    "PhysxTriangleMeshSimplificationPropertiesCfg",
    "RigidBodyBaseCfg",
    "RigidBodyFragment",
    "RigidBodyPropertiesCfg",
    "SDFMeshPropertiesCfg",
    "SchemaFragment",
    "SpatialTendonFragment",
    "SpatialTendonPropertiesCfg",
    "TriangleMeshPropertiesCfg",
    "TriangleMeshSimplificationPropertiesCfg",
    "USD_MESH_COLLISION_CFGS",
    "UsdPhysicsCollisionCfg",
    "UsdPhysicsDriveCfg",
    "UsdPhysicsMeshCollisionCfg",
    "UsdPhysicsRigidBodyCfg",
    "activate_contact_sensors",
    "apply_articulation_root_properties",
    "apply_collision_properties",
    "apply_drive",
    "apply_fixed_tendon_properties",
    "apply_joint_drive_properties",
    "apply_mass_properties",
    "apply_mesh_collision",
    "apply_mesh_collision_properties",
    "apply_namespaced",
    "apply_rigid_body_properties",
    "apply_spatial_tendon_properties",
    "create_world_fixed_joint",
    "define_actuator_properties",
    "define_articulation_root_properties",
    "define_collision_properties",
    "define_deformable_body_properties",
    "define_deformable_curve_properties",
    "define_mass_properties",
    "define_mesh_collision_properties",
    "define_rigid_body_properties",
    "modify_articulation_root_properties",
    "modify_collision_properties",
    "modify_deformable_body_properties",
    "modify_fixed_tendon_properties",
    "modify_joint_drive_properties",
    "modify_mass_properties",
    "modify_mesh_collision_properties",
    "modify_rigid_body_properties",
    "modify_spatial_tendon_properties",
]

from .schemas import (
    MESH_APPROXIMATION_TOKENS,
    PHYSX_MESH_COLLISION_CFGS,
    USD_MESH_COLLISION_CFGS,
    activate_contact_sensors,
    apply_articulation_root_properties,
    apply_collision_properties,
    apply_drive,
    apply_fixed_tendon_properties,
    apply_joint_drive_properties,
    apply_mass_properties,
    apply_mesh_collision,
    apply_mesh_collision_properties,
    apply_namespaced,
    apply_rigid_body_properties,
    apply_spatial_tendon_properties,
    create_world_fixed_joint,
    define_articulation_root_properties,
    define_collision_properties,
    define_deformable_body_properties,
    define_deformable_curve_properties,
    define_mass_properties,
    define_mesh_collision_properties,
    define_rigid_body_properties,
    modify_articulation_root_properties,
    modify_collision_properties,
    modify_deformable_body_properties,
    modify_fixed_tendon_properties,
    modify_joint_drive_properties,
    modify_mass_properties,
    modify_mesh_collision_properties,
    modify_rigid_body_properties,
    modify_spatial_tendon_properties,
)

from .schemas_actuators import (
    define_actuator_properties,
)

from .schemas_cfg import (
    ArticulationRootBaseCfg,
    ArticulationRootFragment,
    BoundingCubePropertiesCfg,
    BoundingSpherePropertiesCfg,
    CollisionBaseCfg,
    CollisionFragment,
    DeformableBodyPropertiesBaseCfg,
    FixedTendonFragment,
    JointDriveBaseCfg,
    JointDriveFragment,
    MassCfg,
    MassFragment,
    MassPropertiesCfg,
    MeshCollisionBaseCfg,
    MeshCollisionFragment,
    RigidBodyBaseCfg,
    RigidBodyFragment,
    SchemaFragment,
    SpatialTendonFragment,
    UsdPhysicsCollisionCfg,
    UsdPhysicsDriveCfg,
    UsdPhysicsMeshCollisionCfg,
    UsdPhysicsRigidBodyCfg,
)
# Forwarded via __getattr__ → isaaclab_newton.sim.schemas.schemas_cfg
from isaaclab_newton.sim.schemas.schemas_cfg import (
    MujocoJointDrivePropertiesCfg as MujocoJointDrivePropertiesCfg,
    MujocoRigidBodyPropertiesCfg as MujocoRigidBodyPropertiesCfg,
    NewtonArticulationRootPropertiesCfg as NewtonArticulationRootPropertiesCfg,
    NewtonCollisionPropertiesCfg as NewtonCollisionPropertiesCfg,
    NewtonJointDrivePropertiesCfg as NewtonJointDrivePropertiesCfg,
    NewtonMaterialPropertiesCfg as NewtonMaterialPropertiesCfg,
    NewtonMeshCollisionPropertiesCfg as NewtonMeshCollisionPropertiesCfg,
    NewtonRigidBodyPropertiesCfg as NewtonRigidBodyPropertiesCfg,
    NewtonSDFCollisionPropertiesCfg as NewtonSDFCollisionPropertiesCfg,
)

# Forwarded via __getattr__ → isaaclab_physx.sim.schemas.schemas_cfg
from isaaclab_physx.sim.schemas.schemas_cfg import (
    ArticulationRootPropertiesCfg as ArticulationRootPropertiesCfg,
    CollisionPropertiesCfg as CollisionPropertiesCfg,
    ConvexDecompositionPropertiesCfg as ConvexDecompositionPropertiesCfg,
    ConvexHullPropertiesCfg as ConvexHullPropertiesCfg,
    DeformableBodyPropertiesCfg as DeformableBodyPropertiesCfg,
    FixedTendonPropertiesCfg as FixedTendonPropertiesCfg,
    JointDrivePropertiesCfg as JointDrivePropertiesCfg,
    MeshCollisionPropertiesCfg as MeshCollisionPropertiesCfg,
    PhysxArticulationRootPropertiesCfg as PhysxArticulationRootPropertiesCfg,
    PhysxCollisionPropertiesCfg as PhysxCollisionPropertiesCfg,
    PhysxConvexDecompositionPropertiesCfg as PhysxConvexDecompositionPropertiesCfg,
    PhysxConvexHullPropertiesCfg as PhysxConvexHullPropertiesCfg,
    PhysxDeformableBodyPropertiesCfg as PhysxDeformableBodyPropertiesCfg,
    PhysxFixedTendonPropertiesCfg as PhysxFixedTendonPropertiesCfg,
    PhysxJointDrivePropertiesCfg as PhysxJointDrivePropertiesCfg,
    PhysxRigidBodyPropertiesCfg as PhysxRigidBodyPropertiesCfg,
    PhysxSDFMeshPropertiesCfg as PhysxSDFMeshPropertiesCfg,
    PhysxSpatialTendonPropertiesCfg as PhysxSpatialTendonPropertiesCfg,
    PhysxTriangleMeshPropertiesCfg as PhysxTriangleMeshPropertiesCfg,
    PhysxTriangleMeshSimplificationPropertiesCfg as PhysxTriangleMeshSimplificationPropertiesCfg,
    RigidBodyPropertiesCfg as RigidBodyPropertiesCfg,
    SDFMeshPropertiesCfg as SDFMeshPropertiesCfg,
    SpatialTendonPropertiesCfg as SpatialTendonPropertiesCfg,
    TriangleMeshPropertiesCfg as TriangleMeshPropertiesCfg,
    TriangleMeshSimplificationPropertiesCfg as TriangleMeshSimplificationPropertiesCfg,
)
